master:
  JCasC:
    enabled: true
    pluginVersion: 1.35
    defaultConfig: true
    configScripts:
      welcome-message: |
       jenkins:
         systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
      shared-libs: |
        unclassified:
          globalLibraries:
            libraries:
            - defaultVersion: "master"
              includeInChangesets: false
              name: "jsl"
              retriever:
                modernSCM:
                  scm:
                    github:
                      configuredByUrl: true
                      credentialsId: "github-token"
                      id: "f82c1b68-4b36-4f85-beaf-5a98bbcd11c0"
                      repoOwner: "vdksystem"
                      repository: "techtalkjenkins-jsl"
                      repositoryUrl: "https://github.com/vdksystem/techtalkjenkins-jsl.git"
                      traits:
                      - gitHubBranchDiscovery:
                          strategyId: 1
                      - originPullRequestDiscoveryTrait:
                          strategyId: 1
                      - gitHubForkDiscovery:
                          strategyId: 1
                          trust: "gitHubTrustPermissions"
      jobs: |
        jobs:
          - script: >
              organizationFolder('example') {
                  description('Demo project for Odessa TechTalks')
                  displayName('TechTalks')
                  triggers {
                      periodicFolderTrigger {
                      interval("3600")
                      }
                  }
                  organizations {
                    github {
                      repoOwner("vdksystem")
                      credentialsId("github-token")
                      traits {
                        cleanBeforeCheckoutTrait()
                        sourceRegexFilter {
                          regex("techtalkjenkins")
                        }
                        gitHubBranchDiscovery {
                          strategyId(1)
                        }
                        originPullRequestDiscoveryTrait {
                          strategyId(1)
                        }
                      }
                    }
                    projectFactories {
                      workflowMultiBranchProjectFactory {
                        scriptPath("app/declarative.Jenkinsfile")
                      }
                    }
                  }
              }
  sidecars:
    configAutoReload:
      enabled: true
  adminPassword: admin
  installPlugins:
    - kubernetes:1.21.2
    - workflow-job:2.36
    - workflow-aggregator:2.6
    - credentials-binding:1.20
    - git:4.0.0
    - kubernetes-credentials-provider:0.13
    - ws-cleanup:0.37
    - pipeline-utility-steps:2.3.1
    - job-dsl:1.76
    - github-organization-folder:1.6
    - custom-tools-plugin:0.7
    - timestamper:1.10
persistence:
  enabled: false